### ISSUE TITLE
Teensy LC support verified?

### ISSUE THREAD

**Issue by BadAlchemy13** [dmadison/ArduinoXInput_Teensy#22]
I have a Teensy LC board but arent seeing any xInput with LC options under Board. I can see that I can set USB type to XInput only? Am I not installing this correctly? I copied all zip file contents to the hardware library and overwrote the folders contents. I had already installed Teensyduino.

**Comment by dmadison** [comment]
>I can see that I can set USB type to XInput only?

Yep, that's all you need.
